---
openshift_cluster_content:
  - object: projectrequest
    content:
      - name: ninja-board-project-dev
        template: "{{ inventory_dir }}/../../.openshift/projects/project.yml"
        action: create
        params_from_vars: "{{ dev }}"
        tags:
          - projects-{{ ninja_board_dev_namespace }}
          - projects
      - name: ninja-board-project
        template: "{{ inventory_dir }}/../../.openshift/projects/project.yml"
        action: create
        params_from_vars: "{{ prod }}"
        tags:
          - projects-{{ ninja_board_prod_namespace }}
          - projects
  - object: rbac
    content:
      - name: ninja-board-rbac
        template: "{{ inventory_dir }}/../../.openshift/templates/rbac.yml"
        action: create
        params_from_vars:
          DEV_NAMESPACE: "{{ ninja_board_dev_namespace }}"
          PROD_NAMESPACE: "{{ ninja_board_prod_namespace }}"
          JENKINS_NAMESPACE: "{{ ninja_board_jenkins_namespace }}"
          ACCESS_NAMESPACE: "{{ access_namespace }}"
        tags:
          - projects-{{ ninja_board_prod_namespace }}
          - projects
          - rbac
  - object: cicd
    content:
      - name: Deploy Jenkins Master
        template: "{{ inventory_dir }}/../../.openshift/templates/jenkins-ephemeral.yml"
        namespace: "{{ ninja_board_dev_namespace }}"
        params_from_vars:
          MEMORY_LIMIT: 2Gi
        tags:
          - cicd
  - object: builds
    content:
      - name: "build-ninja-board"
        template: "{{ inventory_dir }}/../../.openshift/templates/ninja-board-build.yml"
        params_from_vars:
          SOURCE_REPOSITORY_URL: "{{ source_repo }}"
          SOURCE_REPOSITORY_REF: "{{ source_ref }}"
          DEV_NAMESPACE: "{{ ninja_board_dev_namespace }}"
          PROD_NAMESPACE: "{{ ninja_board_prod_namespace }}"
        namespace: "{{ ninja_board_dev_namespace }}"
        tags:
          - projects-{{ ninja_board_dev_namespace }}
          - builds
  - object: deployments
    content:
      - name: "deploy-ninja-board-dev"
        template: "{{ inventory_dir }}/../../.openshift/templates/ninja-board-deployment.yml"
        params_from_vars:
          GITHUB_API_TOKEN: "{{ dev_github_api_token | default(github_api_token, true) }}"
          TRELLO_API_TOKEN: "{{ dev_trello_api_token | default(trello_api_token, true) }}"
          TRELLO_API_KEY: "{{ dev_trello_api_key | default(trello_api_key, true) }}"
          GITLAB_API_TOKEN: "{{ dev_gitlab_api_token | default(gitlab_api_token, true) }}"
          GD_CREDENTIALS: "{{ dev_gd_credentials | default(gd_credentials, true) }}"
          XGRAPHS_PROXY: "{{ dev_xgraphs_proxy | default(xgraphs_proxy, true) }}"
          USERS_LDAP_PROVIDER: "{{ dev_users_ldap_provider | default(users_ldap_provider, true) }}"
        namespace: "{{ ninja_board_dev_namespace }}"
        tags:
          - projects-{{ ninja_board_dev_namespace }}
          - deployments
      - name: "deploy-ninja-board-prod"
        template: "{{ inventory_dir }}/../../.openshift/templates/ninja-board-deployment.yml"
        params_from_vars:
          GITHUB_API_TOKEN: "{{ prod_github_api_token | default(github_api_token, true) }}"
          TRELLO_API_TOKEN: "{{ prod_trello_api_token | default(trello_api_token, true) }}"
          TRELLO_API_KEY: "{{ prod_trello_api_key | default(trello_api_key, true) }}"
          GITLAB_API_TOKEN: "{{ prod_gitlab_api_token | default(gitlab_api_token, true) }}"
          GD_CREDENTIALS: "{{ prod_gd_credentials | default(gd_credentials, true) }}"
          XGRAPHS_PROXY: "{{ prod_xgraphs_proxy | default(xgraphs_proxy, true) }}"
          USERS_LDAP_PROVIDER: "{{ prod_users_ldap_provider | default(users_ldap_provider, true) }}"
        namespace: "{{ ninja_board_prod_namespace }}"
        tags:
          - projects-{{ ninja_board_prod_namespace }}
          - deployments
  - object: front-end
    content:
      - name: "ninja-board-front-end"
        template: "{{ inventory_dir }}/../../react/ninja-react/.openshift/templates/ninja-board-front-end.yml"
        params_from_vars:
          SOURCE_REPOSITORY_URL: "{{ source_repo }}"
          SOURCE_REPOSITORY_REF: "v2"
          DEV_NAMESPACE: {{ ninja_board_dev_namespace }}
        namespace: {{ ninja_board_dev_namespace }}
        tags:
          - projects-{{ ninja_board_dev_namespace }}
          - front-end
  - object: back-end
    content:
      - name: "build-ninja-board-back-end"
        template: "{{ inventory_dir }}/../../.openshift/templates/ninja-board-back-end.yml"
        params_from_vars:
          SOURCE_REPOSITORY_URL: "{{ source_repo }}"
          SOURCE_REPOSITORY_REF: "v2"
          DEV_NAMESPACE: "{{ ninja_board_dev_namespace }}"
        namespace: "{{ ninja_board_dev_namespace }}"
        tags:
          - projects-{{ ninja_board_dev_namespace }}
          - back-end
